In [10]:
import torch
import torch.nn as nn

# requires_grad 조작하기

In [11]:
x = torch.ones(2, 2, requires_grad=True)
print(x)
x.requires_grad_(False)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[1., 1.],
        [1., 1.]])


# .detach() 조작하기

In [12]:
x = torch.ones(2, 2, requires_grad=True)
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)
print(x.requires_grad)

True
False
True


# with torch.no_grad() 활용하기

In [13]:
x = torch.ones(2, 2, requires_grad=True)
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)
y.requires_grad_(True)
print(y.requires_grad)

with torch.no_grad():
    z = x+y
    print(z.requires_grad)

True
False
True
False


# model.eval() 확인해보기

In [14]:
drop = nn.Dropout()
x = torch.ones(1, 10)

# Train
drop.train()
print(drop(x))

# Eval
drop.eval()
print(drop(x))

tensor([[0., 2., 0., 0., 2., 2., 2., 2., 0., 2.]])
tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])
